### ISSUE TITLE
Ongeveer TODOS

### ISSUE THREAD

**Issue by Astronautilus14** [ODDInvictus/ibs3#229]
# TODOS
## Refactor
- [x] Hernoem 'invoice' naar 'boekstuk'
- [x] Transacties
- [ ] Table component
- [ ] Image upload component
- [x] Hernoem 'invoiceId' naar 'boekstuk nummer'
- [x] Vervang middlewares
- [x] Pagination component
- [ ] Lege regels uit streeplijst automatisch weghalen
- [x] Match transactie form herschrijven
   - [ ] Auto complete amount bij selecteren journal  
   - [x] Test alles nog 10x
   - [x] Superforms
   - [x] createTransaction functie
 - [ ] JSON serialize Decimal
 - [x]  Fix hard coded ledger ids
 - [ ] Dubbele - in negatieve journal in ledger view

## Features
- [x] Banktransacties unmatchen
- [x] Maak declaraties ook negatief (ingeleverd statiegeld)
- [x] Laat ledgers zien bij verstuurde sale
- [x] Table met alle transacties die aan een journal zijn gematched
- [x] Saldotransacties matchen
   - [x] Automatisch vanuit streeplijst
   - [x] Handmatig
   - [x] Laten zien hoe een saldo transactie nu gematched is 
- [x] Openstaande betalingen overzicht
- [x] Help pagina 
   - [x] Sale aanmaken
   - [x] Inkoop inboeken
   - [x] PIN transactie verwerken
   - [x] Declaraties 
   - [x] Streeplijst verwerken
- [x] Journals uit de opties halen / lager in de opties zetten wanneer deze volledig is betaald
- [x] Producten en categorien verwijderen wanneer veilig
- [x] Streeplijst bewerken na aanmaken (factuurdatum pas zetten bij het processen van alles wat nog null is)
- [x] Status in sales overzicht
- [x] Ledgers CRUD
- [x] Relaties CRUD
- [x] Producten CRUD
- [x] Product categrieen CRUD
- [x] Sale journal verwijderen wanneer veilig
- [x] Banktransacties uploaden + bekijken
- [x] Banktransacties matchen aan een bepaalde ledger + omschrijving
- [x] Factuur generen
- [x] Declaratie flow
   - [x] Declas inboeken bij een bepaalde ledger
   - [x] Decla opties toevoegen: betaling op rekening of op saldo. Op rekening -> vraag een iban
- [x] Dingen veplaatsen van /financieel naar /ongeveer
   - [x] Streeplijst verwerken
      - [X] UI
      - [X] Journals maken
      - [x] Transacties maken
   - [x] Declaratie overzicht
   - [x] Saldo transacties
   - [x] Saldo overzicht
 - [x] Streeplijst bekijken 
- [x] Factuur inboeken
   - [x] Factuur nummer
- [x] Gematchde transacties laten zien bij journal
- [x] Saldo en transacties in /financieel
 - [x] Status journal 'betaald' of 'onbetaald' in overzicht en journal pagina

## Deployment
- [x] Migraties
  - Transaction table legen
  - Streeplijst table legen
  - Saldo resetten
- [x] Default ledger ids 

## Later ook nog
- [ ] Fix dubbele - op ledger pagina bij een negatieve declaratie
- [ ] Dashboard
   - [ ] Overdatum Journals
   - [ ] openstaande Journal
   - [ ] ongematchte transacties
   - [ ] totaal uitgaven en inkomsten
- [ ] Laatste upload datum
- [ ] Bericht bij beoordelen declaratie
- [ ] Financieel jaar eindigen
- [ ] Reserveringen maken
- [ ] Type ledgers
- [ ] Voorraad telling
- [ ] Boekstuk maken van uit bank matchen
- [ ] Van factuur daadwerkelijk pdf genereren en opslaan
- [x] Laat alle errors is match transaction zien ipv de eerste die hij tegen komt
- [ ] Contributie innen op saldo
- [ ] Support voor groepen
- [ ] Transactie unmatchen: saldo transactie undone maken
- [x] Forceer light mode wanneer invoice printen
- [ ] Default ledgers veranderen
- [ ] 'Product type' in product veranderen in 'default ledger'
- [ ] Prefixes zoals 'declaratie' en 'handmatige transactie' laten zien in forms
- [ ] Je kan meer matchen aan de journal dan zou moeten kunnen als je het opsplitststs over meer dan 1 regel
- [ ] Handmatig saldo transactie aan banktransactie matchen
- [ ] Auto completes
   - [ ] Transactie match resterend bedrag

**Comment by Nierot** [comment]
Contributie is mogelijk doormiddel van cron in de backend, kijk maar hoe strafbakken verdubbelen is geimplementeerd. Enig ding hiermee is dat we hiervoor wel (maandelijks o.i.d.) ff overzichtje moeten emailen zodat mensen hun saldo niet te hard omlaag gaan
